version: '3.8'
services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        ports:
            - ${MONGODB_PORT}:${MONGODB_PORT}
        volumes:
            - mongodb_data:/data/db
    mongo-express:
        image: mongo-express
        container_name: mongo_express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - '8081:8081'
        depends_on:
            - mongo
volumes:
    mongodb_data:
